name: hanafi_mirath_calculator
description: "Hanafi Mirath and Islamic Inheritance Calculator Flutter App with 31 Zawil Furud Rules and 4 Asabah Classes"
publish_to: 'none'
version: 1.2.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.19.0
  fl_chart: ^0.69.0
  share_plus: ^10.0.0
  flutter_staggered_animations: ^1.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
